java 21
baltzell/coatjava-3 pull request #315
Opened 2024-08-21 19:25 UTC by baltzell

2024-12-16 21:20 UTC, c-dilks commented on .github/workflows/maven.yml
> +  groovy_version: 4.0
```suggestion
  groovy_version: 4.x
```

2024-12-16 21:39 UTC, c-dilks commented
ignore validation pipeline failure, since https://github.com/JeffersonLab/clas12-validation/pull/163 is needed.

2024-12-17 15:16 UTC, c-dilks commented
When you're ready to merge this, let's also merge
- https://github.com/JeffersonLab/clas12-timeline/pull/236
- https://github.com/JeffersonLab/clas12-validation/pull/163

2024-12-18 00:13 UTC, baltzell commented
I don't think either of those really need to wait for this.

2024-12-18 15:15 UTC, c-dilks commented
added to java21 project page: https://github.com/orgs/JeffersonLab/projects/45/views/1

2024-12-19 00:50 UTC, c-dilks reviewed
might as well bump these to the latest version that @dependabot proposed

2024-12-19 00:50 UTC, c-dilks commented on common-tools/clas-jcsg/pom.xml
> +      <version>24-ea+5</version>
```suggestion
      <version>24-ea+19</version>
```

2024-12-19 00:50 UTC, c-dilks commented on common-tools/clas-jcsg/pom.xml
> +      <version>24-ea+5</version>
```suggestion
      <version>24-ea+19</version>
```

2024-12-19 00:50 UTC, c-dilks commented on common-tools/clas-geometry/pom.xml
> +      <version>24-ea+5</version>
```suggestion
      <version>24-ea+19</version>
```

2025-01-06 19:55 UTC, baltzell commented on common-tools/clas-jcsg/pom.xml
> +      <version>24-ea+5</version>
looks like this would require java 22

2025-05-31 00:27 UTC, c-dilks approved these changes, later dismissed

2025-09-03 21:00 UTC, c-dilks requested changes
Should also bump the release parameter:

https://github.com/JeffersonLab/coatjava/blob/416c3a3ce0ce91109c344b7f6fed32b6db329609/pom.xml#L247-L255

2025-09-03 21:25 UTC, closed without merging