implemented a new service to be used in DCALIGN cooking,
baltzell/coatjava-3 pull request #380
Opened 2024-12-04 20:07 UTC by gavalian

New banks in the output should help with ai training and validation

2024-12-05 01:52 UTC, baltzell requested changes
let's remove the ide boilerplate and commented-out stuffs

2024-12-05 14:17 UTC, raffaelladevita requested changes

2024-12-05 14:17 UTC, raffaelladevita commented on etc/bankdefs/hipo4/neuralnetwork.json
> +	{
Can the new bank be added at the bottom of the file, so that they are ordered by item?

2024-12-05 14:17 UTC, raffaelladevita commented on etc/services/dcalign.yaml
> +  - class: org.jlab.service.mltn.MLDCEngine
dcalign.yaml is really only used for straight tracks/alignment runs. The new service should be added to data-ai.yaml or data-cv.yaml or data-aicv.yaml.

2024-12-05 14:17 UTC, raffaelladevita commented on reconstruction/mltn/src/main/java/org/jlab/service/mltn/MLDCEngine.java
> +        if(de.hasBank("TimeBasedTrkg::AITracks")&&de.hasBank("TimeBasedTrkg::AIClusters")){
Note that the banks with the AI prefix are created only when data-aicv.yaml is used. When data-ai.yaml is used, the tracking banks have the TB prefix even if AI tracking is used.

2025-01-03 15:11 UTC, raffaelladevita commented on etc/bankdefs/hipo4/neuralnetwork.json
> +	{
done in https://github.com/JeffersonLab/coatjava/pull/380/commits/007e11ffb9c113a657c0396e72f93064e7e22500

2025-01-03 15:15 UTC, raffaelladevita commented
As soon as the changes to dcalign.yaml are reverted and https://github.com/JeffersonLab/coatjava/pull/380#pullrequestreview-2480256094 is taken care of, this PR can be merged

2025-01-30 14:57 UTC, raffaelladevita requested changes

2025-01-30 14:57 UTC, raffaelladevita commented on reconstruction/mltn/src/main/java/org/jlab/service/mltn/MLDCEngine.java
> +/*
this is the commented text that should be removed

2025-01-30 22:57 UTC, baltzell submitted a review, later dismissed

2025-02-24 19:14 UTC, raffaelladevita approved these changes

2025-10-25 02:22 UTC, closed without merging